### ISSUE TITLE
The sensors don't update themselves

### ISSUE THREAD

**Issue by Busak007** [RomRider/ha_nicehash#27]
the sensors don't update themselves. They only have new values ​​when I give the "Reload" integration

**Comment by RoaringSon** [comment]
Same here, getting this error in the logs:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/config/custom_components/nicehash/switch.py", line 70, in _update_entities
    for dev in rig.get("devices"):
TypeError: 'NoneType' object is not iterable`

**Comment by RACMan2527** [comment]
Same.  Seems to be artifact of August builds for HA?
I renewed my NiceHash API, yet the values for the miners only update when 'reload integration' is selected for this NiceHash component.
Using version ecd72e0

**Comment by jagauthier** [comment]
Any update on this? I just loaded integration and the sensors do not update.

**Comment by RudiPohlen** [comment]
Same here. Installed the Integration today, but the sensor newer update themselv.

**Comment by turemao** [comment]
Same here, The miners counters only update when 'reload integration' is selected for this NiceHash component.
Have you found the solution to this issue?

Anyway, great job to the developer.

**Comment by RudiPohlen** [comment]
No, I have uninstalled it. It's useless if it doesn't update itself

**Comment by jagauthier** [comment]
I messed with it for awhile, but I do not know much about HA integrations.  The author seems to have lost interest in this.

**Comment by turemao** [comment]
I used this workaround:

edit configuration.yaml
`shell_command:
  nice_restart: "/usr/bin/curl -X 'POST' -H 'authorization: Bearer <token>' http://localhost:8123/api/config/config_entries/entry/integration_id/reload"`

automation:
`- id: '1713952324533'
  alias: Reload Nicehash Integration
  trigger:
  - platform: time_pattern
    minutes: '5'
  condition: []
  action:
  - service: shell_command.nice_restart
    data: {}
  mode: single
  `

where:
"token" is long lived token I’ve generated in profile section
"integration_id" from nicehash entry inside config/.storage/core.config_entries file

**Comment by jagauthier** [comment]
@turemao That's cool. Does restarting the integration every 5 minutes cause any performance issues?

**Comment by turemao** [comment]
@jagauthier The Trigger is once per hour,  the 5th minute of every hour, that's enough for me.

**Comment by jagauthier** [comment]
Nice. I will re-evaluate. Thanks for the tip!

**Comment by 928driver** [comment]
@jagauthier @turemao , are you still using this Nice Hash integration in HA? I have used it for quite many months without any issues, just needed to add the automation to restart the integration at fixed intervalls to update values. But today values from Nice Hash became unavalailable for both me and my brother in his HA, did you experience the same?

**Comment by jagauthier** [comment]
I have stopped using it.  But I just installed it again, and it "won't connect"

**Comment by turemao** [comment]
> @jagauthier @turemao , are you still using this Nice Hash integration in HA? I have used it for quite many months without any issues, just needed to add the automation to restart the integration at fixed intervalls to update values. But today values from Nice Hash became unavalailable for both me and my brother in his HA, did you experience the same?

@928driver Same behavior for me, unfortunately Nicehash requires KYC tier 2 for this kind of request :
{"code":2134,"message":"KYC tier 2 is required for this operation."}]}
